Add initial commit for SpEyeGaze
TeamGleason/SpeakFaster pull request #1
Opened 2021-04-26 15:29 UTC by joncamp

Baseline utility for data collection. UI is (reasonably) eyegaze friendly (once launched from task tray). Supports collecting keystrokes into a protobuf, as well as capturing screenshots (currently disabled). Provides the ability for recording to be paused.

2021-04-27 20:20 UTC, joncamp commented
Example captured keystrokes, as dumped by the python dumping tool:

❯ python .\SpEyeGaze_Decoder.py C:\Users\joncamp\AppData\Local\SpEyeGaze\Keypresses\Keypresses-20210427T100450f.bin
Key:RShiftKey Timestamp:1619543038
Key:T Timestamp:1619543039
Key:H Timestamp:1619543039
Key:I Timestamp:1619543039
Key:S Timestamp:1619543039
Key:Space Timestamp:1619543039
Key:S Timestamp:1619543039
Key:H Timestamp:1619543040
Key:O Timestamp:1619543040
Key:U Timestamp:1619543040
Key:L Timestamp:1619543040
Key:D Timestamp:1619543040
Key:Space Timestamp:1619543040
Key:B Timestamp:1619543040
Key:E Timestamp:1619543040
Key:Space Timestamp:1619543040
Key:R Timestamp:1619543041
Key:E Timestamp:1619543041
Key:C Timestamp:1619543041
Key:O Timestamp:1619543041
Key:R Timestamp:1619543041
Key:D Timestamp:1619543041
Key:E Timestamp:1619543042
Key:D Timestamp:1619543042
Key:Space Timestamp:1619543042
Key:B Timestamp:1619543042
Key:E Timestamp:1619543042
Key:C Timestamp:1619543042
Key:A Timestamp:1619543043
Key:U Timestamp:1619543043
Key:S Timestamp:1619543043
Key:E Timestamp:1619543043
Key:Space Timestamp:1619543043
Key:B Timestamp:1619543043
Key:A Timestamp:1619543043
Key:L Timestamp:1619543043
Key:A Timestamp:1619543044
Key:B Timestamp:1619543044
Key:O Timestamp:1619543044
Key:L Timestamp:1619543044
Key:K Timestamp:1619543044
Key:A Timestamp:1619543044
Key:Space Timestamp:1619543045
Key:I Timestamp:1619543045
Key:S Timestamp:1619543045
Key:Space Timestamp:1619543045
Key:R Timestamp:1619543045
Key:U Timestamp:1619543045
Key:N Timestamp:1619543045
Key:N Timestamp:1619543046
Key:I Timestamp:1619543046
Key:N Timestamp:1619543046
Key:G Timestamp:1619543046
Key:Space Timestamp:1619543046
Key:A Timestamp:1619543046
Key:N Timestamp:1619543046
Key:D Timestamp:1619543046
Key:Space Timestamp:1619543046
Key:R Timestamp:1619543055
Key:E Timestamp:1619543055
Key:C Timestamp:1619543056
Key:O Timestamp:1619543056
Key:R Timestamp:1619543056
Key:D Timestamp:1619543056
Key:I Timestamp:1619543056
Key:N Timestamp:1619543056
Key:G Timestamp:1619543056
Key:Space Timestamp:1619543056
Key:I Timestamp:1619543056
Key:S Timestamp:1619543057
Key:Space Timestamp:1619543057
Key:O Timestamp:1619543057
Key:N Timestamp:1619543057
Key:Return Timestamp:1619543058
Key:RShiftKey Timestamp:1619543078
Key:A Timestamp:1619543078
Key:N Timestamp:1619543078
Key:D Timestamp:1619543079
Key:Space Timestamp:1619543079
Key:N Timestamp:1619543079
Key:O Timestamp:1619543079
Key:W Timestamp:1619543079
Key:Space Timestamp:1619543079
Key:B Timestamp:1619543080
Key:A Timestamp:1619543080
Key:C Timestamp:1619543080
Key:K Timestamp:1619543080
Key:Space Timestamp:1619543080
Key:O Timestamp:1619543081
Key:N Timestamp:1619543081
Key:OemPeriod Timestamp:1619543081

2021-04-28 02:22 UTC, TeamGleasonDev commented
@joncamp  Please add some usage documentation in the form of a couple of markdown readme files for each subproject.

2021-04-28 02:26 UTC, TeamGleasonDev commented on SpEyeGaze/SpEyeGaze/FormMain.cs
> +        readonly string keypressesPath = Path.Combine(
Build these off baseFilePath rather than duplicating.

2021-04-28 02:40 UTC, TeamGleasonDev requested changes

2021-04-28 02:40 UTC, TeamGleasonDev commented on SpEyeGaze/SpEyeGaze/FormMain.cs
> +        enum RecordingState
Feels like this should just be a bool IsRecording

2021-04-28 02:40 UTC, TeamGleasonDev commented on SpEyeGaze/SpEyeGaze/FormMain.cs
> +        readonly string keypressesPath = Path.Combine(
Build these off baseFilePath rather than duplicating.

2021-04-28 02:40 UTC, TeamGleasonDev commented on SpEyeGaze/SpEyeGaze/FormMain.cs
> +        private void btnOff_Click(object sender, EventArgs e)
Toggle button with color indicator?

2021-04-28 02:40 UTC, TeamGleasonDev commented on SpEyeGaze/SpEyeGaze/FormMain.cs
> +            Application.Exit(); // TODO Exit seems to be throwing exception, need to investigate
Close the window instead and let the app terminate "naturally".

2021-04-28 02:40 UTC, TeamGleasonDev commented on SpEyeGaze/SpEyeGaze/FormMain.cs
> +        private void notifyIcon_MouseDoubleClick(object sender, MouseEventArgs e)
Can this be hooked w/ single click too?  Double click is touch unfriendly.

2021-04-28 02:40 UTC, TeamGleasonDev commented on SpEyeGaze/SpEyeGaze/FormMain.cs
> +            notifyIcon.Icon = new Icon("Assets\\Recording" + (isRecording ? "On" : "Off") + ".ico");
While fancy, isn't terribly readable.  Would prefer a simple "if (isRecording) new Icon(...) else new Icon(...)

2021-04-28 02:40 UTC, TeamGleasonDev commented on SpEyeGaze/SpEyeGaze/FormMain.cs
> +                "Recordding " + (currentRecordingState == RecordingState.RecordingOn ? "On" : "Off"),
typo

2021-04-28 02:40 UTC, TeamGleasonDev commented on SpEyeGaze/SpEyeGaze/FormMain.cs
> +            // Note: This seems to only capture the primary display. For most systems
Do not know of any SGDs that are multi-display today.

2021-04-28 02:40 UTC, TeamGleasonDev commented on SpEyeGaze/SpEyeGaze/FormMain.cs
> +        private static readonly string StartupKey = "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run";
Could we use the 'shortcut in a folder' approach rather than the 'run key in the registry'?  It's a bit more discoverable / management to 'real world users':

APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup

2021-04-28 02:40 UTC, TeamGleasonDev commented on SpEyeGaze/SpEyeGaze/Keylogger.cs
> +            UnhookWindowsHookEx(_hookID);
Does this have a potential null ref issue?  It looks like it will never be IntPtr.Zero, but for defense in depth it may be good to check.

2021-04-28 02:40 UTC, TeamGleasonDev commented on SpEyeGaze/SpEyeGaze/Keylogger.cs
> +        [DllImport("user32.dll", CharSet = CharSet.Auto, SetLastError = true)]
Prefer to see these pulled out to a separate Win32/Interop.cs file.

2021-04-28 12:33 UTC, TeamGleasonDev commented
See PR on your PR for some changes which make things work a little better.

2021-04-28 15:30 UTC, joncamp commented on SpEyeGaze/SpEyeGaze/FormMain.cs
> +        enum RecordingState
I will go ahead and swap to IsRecording for now. The thought behind the enum was that we have somewhat of a tri-state scenario. There is the concept of recording being enabled vs. recording actually occurring.

2021-04-28 15:34 UTC, joncamp commented on SpEyeGaze/SpEyeGaze/FormMain.cs
> +        readonly string keypressesPath = Path.Combine(
Building them all that way was my initial thought. CS0236 will get thrown if we initialize at the class level. Moved the initialization to the class constructor so we get the best of both worlds.

2021-04-28 15:42 UTC, joncamp commented on SpEyeGaze/SpEyeGaze/FormMain.cs
> +        private void notifyIcon_MouseDoubleClick(object sender, MouseEventArgs e)
Sure. There are 4 events - click, doubleclick, mouseclick and mousedoubleclick...will hook all 4 in the short term. Need to do a quick check to see what the difference is between the mouse and non-mouse versions...

2021-04-28 15:47 UTC, joncamp commented on SpEyeGaze/SpEyeGaze/FormMain.cs
> +        private static readonly string StartupKey = "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run";
Yeah, I am fine with either. This code wasn't hooked up anyway. I agree - adding a shortcut in startup is a good approach and one I was considering.

2021-04-28 16:54 UTC, joncamp commented on SpEyeGaze/SpEyeGaze/FormMain.cs
> +        private void notifyIcon_MouseDoubleClick(object sender, MouseEventArgs e)
Click events seem to work same as the mouse events, so removed the two redundant event handlers.

2021-04-28 16:57 UTC, joncamp commented on SpEyeGaze/SpEyeGaze/Keylogger.cs
> +            UnhookWindowsHookEx(_hookID);
Added an IntPtr.Zero check, but the Unhook seems to handle it gracefully even if it did occur.

2021-04-28 17:22 UTC, joncamp commented on SpEyeGaze/SpEyeGaze/FormMain.cs
> +        private static readonly string StartupKey = "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run";
https://www.softwarepronto.com/2020/07/creating-windows-shortcuts-links-with.html seems to indicate a potential incompatibility between .net Core 3.x/.net 5 and the creation of a custom shortcut via COM. Need to see if there is another way...

2021-04-28 17:23 UTC, joncamp commented on SpEyeGaze/SpEyeGaze/FormMain.cs
> +            // Note: This seems to only capture the primary display. For most systems
Agreed. Multi-monitor was not a major concern. More of a note regarding the fact that the code, as written, doesn't handle multi-monitor configurations (at least my multi-monitor configuration).

2021-04-29 13:07 UTC, merged

2021-04-29 15:32 UTC, joncamp commented on SpEyeGaze/SpEyeGaze/FormMain.cs
> +        private static readonly string StartupKey = "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run";
Delayed to future checkin