Data contribution agreement: Add clarifications and additional info
TeamGleason/SpeakFaster pull request #28
Opened 2021-05-13 18:12 UTC by caisq

- Clarify that the data collection application will allow starting and ending data collection sessions and deleting previously-collected data
- Explicitly mention Google as a partner
- Fix typo and punctuation

2021-05-13 19:58 UTC, TeamGleasonDev commented on Legal/SpeakFaster_Data_Contribution_Agreement.md
> +Team Gleason Foundation may share the Research Data with contractors and partners, including but not limited to Google LLC, under obligations of confidentiality to annotate the data, create other met
Let's not include this here.  Instead, the council for TG is drafting another short document which is an explicit license of the data between TG and Google LLC so that we can meet the request of your council that Google is explicitly named as a recipient of the data.

2021-05-13 20:00 UTC, TeamGleasonDev requested changes

2021-05-13 20:00 UTC, TeamGleasonDev commented on Legal/SpeakFaster_Data_Contribution_Agreement.md
> +The Application will allow you to start and end data recording at any time. The Application will additionally provide options for you to delete previously-recorded data.
Data deletion will be handled via email request, as described in the last section, rather than via application functionality.

We may add data review and deletion to the app at a future date, but I don't want to encode this into the data collection license.

2021-05-14 00:34 UTC, caisq commented on Legal/SpeakFaster_Data_Contribution_Agreement.md
> +Team Gleason Foundation may share the Research Data with contractors and partners, including but not limited to Google LLC, under obligations of confidentiality to annotate the data, create other met
SG. Reversed the change in this paragraph.

2021-05-14 00:34 UTC, caisq commented on Legal/SpeakFaster_Data_Contribution_Agreement.md
> +The Application will allow you to start and end data recording at any time. The Application will additionally provide options for you to delete previously-recorded data.
OK. Reversed the change in this paragraph.

2021-05-17 19:36 UTC, TeamGleasonDev approved these changes

2021-05-17 19:37 UTC, merged