Observer: Record audio from microphone
TeamGleason/SpeakFaster pull request #47
Opened 2021-06-29 17:30 UTC by caisq

File format:
- The audio files are named in the pattern of `20210629T132215079-MicWaveIn.flac`, which is consistent with the keypresses protobuf files and the screenshot jpg files.
- The audio is sampled at 16000 Hz mono (single channel). 
- To save space, the [FLAC encoding](https://xiph.org/flac/) is used. The FLAC format is supported by services such as [Google Cloud speech-to-text](https://cloud.google.com/speech-to-text/docs/encoding)
- Each .flac file is approximately 1-minute long.

Other info:
- The added audio recording feature follows the existing on/off control based on system-tray icon clicks.

Added dependencies:
- NAudio for reading audio input from microphone
- FlacBox for FLAC encoding

2021-06-30 17:07 UTC, vsubhashini approved these changes
Thanks! This is neat.

2021-07-01 02:40 UTC, TeamGleasonDev requested changes

2021-07-01 02:40 UTC, TeamGleasonDev commented on Observer/SpeakFasterObserver/Upload.cs
> +            //_client = new AmazonS3Client(spo.GetAWSCredentials(sf), spo.Region);
Should file a new bug on having this auto-disable if the spo.GetAWSCredentials doesn't find them.

Perhaps should have a 'mock upload' that instead dumps the files to a folder on a local disk so you can experience what the uploaded data would look like.

2021-07-01 02:40 UTC, TeamGleasonDev commented on Observer/SpeakFasterObserver/AudioInput.cs
> +        private void WaveDataAvailable(object sender, WaveInEventArgs e)
Rather than write to buffer and then dump to file on 'tick', I would write directly to a file and then rotate files on 'tick'.  File writing goes through a write cache on Windows, so you're not saving much perf here and I think you would simplify the code and reduce threading concerns with this approach.

You could then lock on the file object itself to make it clear that what you are protecting against is multiple writers against the same file.

2021-07-01 02:40 UTC, TeamGleasonDev commented on Observer/SpeakFasterObserver/AudioInput.cs
> +                    FlacStreaminfo streamInfo = new FlacStreaminfo();
Please use an [object initializer](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/how-to-initialize-objects-by-using-an-object-initializer).

2021-07-01 02:40 UTC, TeamGleasonDev commented on Observer/SpeakFasterObserver/FormMain.cs
> +            var timestamp = $"{DateTime.Now:yyyyMMddTHHmmssfff}";
Dupe definition line 148, feels like an important line to not duplicate -- especially, ah, since I wrote a bug here with 24h/12h timestamp generation that corrupted some of the data logging that @joncamp had to come in and clean up ¯\\_(ツ)_/¯

2021-07-01 02:40 UTC, TeamGleasonDev commented on Observer/SpeakFasterObserver/FormMain.cs
>          static bool balabolkaRunning = false;
See line 20, we have a toggle for turning on and off screenshot recording so the user can control the type of logging that is occurring.  I think we definitely want to have the same level of choice here and we're going to want to default audio (and screenshot) recording to off.

UX consideration, do we want to have different icons for 'low logging' and 'high logging' indications?  E.g. Logging just speech output vs logging which includes conversational context (audio, screenshots, photos)?

2021-07-01 02:40 UTC, TeamGleasonDev commented on Observer/SpeakFasterObserver/FormMain.cs
> +            var micWaveInFilePath = Path.Combine(
Formatting is 'some of this, some of that'.  All on one line or separate the parameters on new lines?  One or the other, consistency preferred.

2021-07-01 02:40 UTC, TeamGleasonDev commented on Observer/SpeakFasterObserver/AudioInput.cs
> +                throw new NotSupportedException(
Unhandled exception.  Bad user experience if triggered.  Would prefer a messagebox + termination or a silent failure or a Debug.Assert to an unhandled exception user experience.

Note that we don't have an exception reporting service hooked up to this app yet, so an unhandled exception just spews to the user and we don't get notification.  If we are going to allow unhandled exceptions, we should add an app-wide unhandled exception handler that turns into a copyable messagebox with an email address to send to.  Hmm, we have an example of this somewhere that we should be able to find.  Let's file a bug on this too.

2021-07-01 02:40 UTC, TeamGleasonDev commented on Observer/SpeakFasterObserver/AudioInput.cs
> +        private bool isRecording = false;  // TODO(cais): Thread safety?
Looks like [WaveIn already has isRecording protection built in](https://github.com/naudio/NAudio/blob/fb35ce8367f30b8bc5ea84e7d2529e172cf4c381/NAudio.WinForms/WaveIn.cs#L213), and it [uses a volatile bool](https://github.com/naudio/NAudio/blob/fb35ce8367f30b8bc5ea84e7d2529e172cf4c381/NAudio.WinForms/WaveIn.cs#L16) for thread safety.

2021-07-02 02:39 UTC, caisq reviewed
Thanks for the review!

2021-07-02 02:39 UTC, caisq commented on Observer/SpeakFasterObserver/FormMain.cs
>          static bool balabolkaRunning = false;
Good point. Done adding a tool strip menu item titled "Record Audio from Microphone" and hooking it up with the logic in a way similar to the screenshots control. 

Note I set the default to true for recording from microphone, because it does seem to work and doesn't incur excessive CPU or RAM usage.

2021-07-02 02:39 UTC, caisq commented on Observer/SpeakFasterObserver/AudioInput.cs
> +                throw new NotSupportedException(
Fair point. I filed #64 for adding an app-wide exception handling mechanism and added a TODO item here. For now I'll just leave this exception as is. I think the 16-bit audio format is fairly common and the likelihood of finding it not support on a Surface device is low.

2021-07-02 02:39 UTC, caisq commented on Observer/SpeakFasterObserver/AudioInput.cs
> +        private void WaveDataAvailable(object sender, WaveInEventArgs e)
Done. I rewrote the code in this file to make it stream to a file in real time. 

Note this change introduces a new intricacy: This new real-time file writing scenario is unprecedented in Observer. We need to prevent the uploader (Upload.cs) from uploading in-progress files like the .flac.InProgress files written by `AudioInput`. I added some logic to Upload.cs for that purpose. I also did some refactoring to collect all the file name and path logic in a single class (the new FileNaming.cs).

2021-07-07 03:16 UTC, caisq commented
Gentle ping @TeamGleasonDev Please take another look when you get a chance.

2021-07-08 20:15 UTC, TeamGleasonDev commented on Observer/SpeakFasterObserver/Upload.cs
> +            //_client = new AmazonS3Client(spo.GetAWSCredentials(sf), spo.Region);
Filed #65.

2021-07-08 20:28 UTC, TeamGleasonDev commented on Observer/SpeakFasterObserver/AudioInput.cs
> +        private bool isRecording = false;  // TODO(cais): Thread safety?
FYI, if you look at the WaveIn code, StopRecording() just returns if !isRecording, so this code is redundant.  But redundant is find too, since it's not obviouls what the WaveIn behavior is.

2021-07-08 20:28 UTC, merged