Add support for Blink(1) Led for external feedback
TeamGleason/SpeakFaster pull request #77
Opened 2021-09-02 18:03 UTC by joncamp

2021-09-02 20:50 UTC, TeamGleasonDev commented
Please update readme to reference the hardware being supported and where to order (e.g. https://www.amazon.com/gp/product/B07Q8944QK)

2021-09-03 03:13 UTC, caisq requested changes
First round of comments, focusing on the Python part.

I'll comment on the C# (LED) part tomorrow.

2021-09-03 03:13 UTC, caisq commented on Observer/SpeakFasterObserver Decoder/process_keypresses.py
> +                self.character_count - (actual_num_of_keystrokes)
Remove this pair of parentheses please. They are superfluous.

2021-09-03 03:13 UTC, caisq commented on Observer/SpeakFasterObserver Decoder/process_keypresses.py
> +        is_next_gaze_typed, _next_delta_timestamp = is_key_gaze_initiated(
Is `_next_delta_timestamp` used? If not, the more idiomatic approach is to assign it to a variable named `_`. This helps reducing confusion.

See: https://google.github.io/styleguide/pyguide.html#214-decision

2021-09-03 19:39 UTC, caisq commented on Observer/SpeakFasterObserver/FormMain.cs
> +                    blink1.Set(Color.Red);
The code looks fine to me except a question I have below, but it turns out that we may not have the same hardware LED, so it may not be possible for me to do the actual testing of it on my end. But I'm willing to trust your code. 

The LED I have is: [Sparklet Si2](https://www.amazon.com/Sparklet-256X-Round-Color-Display/dp/B08FHGGC7N/ref=asc_df_B08FHGGC7N/?tag=hyprod-20&linkCode=df0&hvadid=459623382939&hvpos=&hvnetw=g&hvrand=1137575804737654910&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=1018145&hvtargid=pla-956906240085&psc=1)

What kind of LED do you have?

2021-09-03 19:41 UTC, caisq commented on Observer/SpeakFasterObserver/FormMain.cs
> +                blink1.TurnOff();
This is partly pre-existing. But `ExitApplication()` is called when the user clicks the exit button. What if the app is terminated in another way (say, system-initiated app shutdown when the user logs out)? Is there a lifecycle callback that can be used to catch such events and make sure that the LED is turned off and avoids the "cry wolf" scenario? If the LED is not turned off properly, it may be left on for too long and the user and people are them will just learn to ignore it.

2021-09-07 19:50 UTC, joncamp commented on Observer/SpeakFasterObserver/FormMain.cs
> +                    blink1.Set(Color.Red);
There are two devices that have been discussed. The Sparklet Si2 like you have, the [Sparklet All-in-One](https://siliconsquared.com/sparkletallinone/), and the [blink(1)](https://blink1.thingm.com/). This code targets the [blink(1)](https://smile.amazon.com/ThingM-Blink-USB-RGB-BLINK1MK3/dp/B07Q8944QK/) because it was quick to implement. The Sparklet does not have an API that is easily accessible at this time, so for expediency I switched to the blink.

2021-09-07 20:26 UTC, joncamp commented on Observer/SpeakFasterObserver/FormMain.cs
> +                blink1.TurnOff();
Good point. Updated the code to blink rather than turn the LED on. This should address the issue you mention.

2021-09-07 20:30 UTC, joncamp commented
> Please update readme to reference the hardware being supported and where to order (e.g. https://www.amazon.com/gp/product/B07Q8944QK)

Done - in latest commit

2021-09-07 20:31 UTC, merged