[Observer] Demonstrate how to use Azure Speaker ID in real time
TeamGleason/SpeakFaster pull request #86
Opened 2021-09-22 02:24 UTC by caisq

in conjunction with Google Cloud ASR and diarization to recognize known speakers.

The code assumes that speakers have been enrolled and that their profile IDs are stored in a .json file
pointed to by the `SPEAK_FASTER_SPEAKER_ID_CONFIG` environment variable.
The .json file should additionally contain the Azure speech subscription key and the Azure endpoint.

2021-09-23 18:13 UTC, vsubhashini approved these changes
This is cool. Thank you!

2021-09-24 05:41 UTC, TeamGleasonDev requested changes

2021-09-24 05:41 UTC, TeamGleasonDev commented on Observer/SpeakFasterObserver/AudioAsr.cs
> +            string configPath = Environment.GetEnvironmentVariable(
Environment variables are much harder to set in Windows, so this is not typically a pattern that is used.

Would prefer that you use a fixed path to a settings file rather than rely on environment variable for the path.

2021-09-24 05:41 UTC, TeamGleasonDev commented on Observer/SpeakFasterObserver/AudioAsr.cs
> +            string configPath = Environment.GetEnvironmentVariable(
SPO is already using a settings file to load info like this, see:

https://github.com/TeamGleason/SpeakFaster/blob/main/Observer/SpeakFasterObserver/Properties/Settings.settings

2021-09-24 05:41 UTC, TeamGleasonDev commented on Observer/SpeakFasterObserver/AudioAsr.cs
> +                    endTime = wordInfo.EndTime.Seconds + wordInfo.EndTime.Nanos / 1e9;
Ya know, I didn't even know you could use scientific notation in C# numbers.  Never seen it used before.

Learn something new every day!

2021-09-24 05:41 UTC, TeamGleasonDev commented on Observer/SpeakFasterObserver/AudioAsr.cs
> +                Array.Copy(
FYI: https://docs.microsoft.com/en-us/dotnet/api/system.buffer?view=net-5.0

Not sure if it's cleaner in this case, but I believe has more convenient methods for this type of manipulation.

2021-09-24 05:41 UTC, TeamGleasonDev commented on Observer/SpeakFasterObserver/AudioAsr.cs
> +        private static readonly bool ENABLE_SPEAKER_ID = true;
"private const" stylisticly prefered to "private static readonly" in cases like this with a const initializer.

2021-09-24 05:41 UTC, TeamGleasonDev commented on Observer/SpeakFasterObserver/AudioAsr.cs
> +                Debug.WriteLine(
Typically don't like to see Debug.WriteLine in production code, as this ends up hiding errors when the code is run with no debugger attached.

My preference is to 'fail loud', e.g. throw a messagebox and exit, as I've seen lots of hard to uncover 'silently failed 30 function calls ago' in my time...

2021-09-24 05:41 UTC, TeamGleasonDev commented on Observer/SpeakFasterObserver/AudioAsr.cs
> +using Newtonsoft.Json.Linq;
I try hard not to use Newtonsoft.Json, as it's a big library that brings in lots of dependencies.

JSON .NET Framework library used to suck pretty hard, so you see a lot of Newtonsoft.Json out in open source these days.  This got rewritten for https://docs.microsoft.com/en-us/dotnet/api/system.text.json?view=net-5.0 to be a bit better, so I try and rely on that whenever possible.

2021-09-24 05:43 UTC, TeamGleasonDev commented on Observer/SpeakFasterObserver/AudioAsr.cs
> +                    $"Erorr: Speaker ID HTTP response contains error: {speakerIdResponse.StatusCode}: " +
Error with your Erorr.

2021-10-01 13:54 UTC, caisq commented
@TeamGleasonDev Gentle ping. Do you have any further comments?

2021-10-01 14:31 UTC, merged